### ISSUE TITLE
Sometimes app crashes with "The render was aborted by the server without a reason" (Unable to enqueue)

### ISSUE THREAD

**Issue by emilgpa** [wakujs/waku#756]
I don't know why it happens. I can't isolate it to reproduce this error. It just happens sometimes. I put the log:

```
Error: The render was aborted by the server without a reason.
    at abort (/Users/emgp/Projects/example_app/clients/browser/node_modules/.pnpm/react-dom@19.0.0-rc-fb9a90fa48-20240614_react@19.0.0-rc-fb9a90fa48-20240614/node_modules/react-dom/cjs/react-dom-server.edge.development.js:7074:17)
    at Object.cancel (/Users/emgp/Projects/example_app/clients/browser/node_modules/.pnpm/react-dom@19.0.0-rc-fb9a90fa48-20240614_react@19.0.0-rc-fb9a90fa48-20240614/node_modules/react-dom/cjs/react-dom-server.edge.development.js:8620:21)
    at readableByteStreamControllerCancelSteps (node:internal/webstreams/readablestream:3022:37)
    at [kCancel] (node:internal/webstreams/readablestream:1166:12)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at readableStreamCancel (node:internal/webstreams/readablestream:1887:5)
    at node:internal/webstreams/readablestream:1439:15
    at complete (node:internal/webstreams/readablestream:1323:9)
    at shutdownWithAnAction (node:internal/webstreams/readablestream:1319:5)
    at node:internal/webstreams/readablestream:1438:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node:internal/webstreams/transformstream:488
    throw new ERR_INVALID_STATE.TypeError('Unable to enqueue');
    ^

TypeError: Invalid state: Unable to enqueue
    at new NodeError (node:internal/errors:405:5)
    at transformStreamDefaultControllerEnqueue (node:internal/webstreams/transformstream:488:11)
    at TransformStreamDefaultController.enqueue (node:internal/webstreams/transformstream:301:5)
    at Timeout._onTimeout (file:///Users/emgp/Projects/example_app/clients/browser/node_modules/.pnpm/waku@0.21.0-alpha.2_react-dom@19.0.0-rc-fb9a90fa48-20240614_react-server-dom-webpack@19.0.0-r_loaivdwzpiimz52uywzu27muau/node_modules/waku/dist/lib/renderers/html-renderer.js:109:32)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 'ERR_INVALID_STATE'
}
```

**Comment by dai-shi** [comment]
@emilgpa Which version are you using?

@himself65 Is it related something we fixed (or not?) recently?

**Comment by emilgpa** [comment]
@dai-shi I forgot to mention it: version 0.21.0-alpha.2

**Comment by dai-shi** [comment]
Hm, it might be something different from what I imagined. (AFAIR, @himself65 found a way to reproduce a similar error.)

**Comment by himself65** [comment]
Should be fixed in https://github.com/dai-shi/waku/commit/d315ceb5540f23e97997a3dbe7139a921a5739f9

**Comment by himself65** [comment]
I think because react will hold a stream to be locked when it throws an error and cause upstream hono cannot process correctly.

**Comment by dai-shi** [comment]
> Should be fixed in [d315ceb](https://github.com/dai-shi/waku/commit/d315ceb5540f23e97997a3dbe7139a921a5739f9)

That's included in 0.21.0-alpha.2. 🤔

**Comment by himself65** [comment]
let me check

**Comment by dai-shi** [comment]
> Error: The render was aborted by the server without a reason.

I saw it when developing something. It happens when I restarted the server?

**Comment by dai-shi** [comment]
`npm run examples:dev:12_css` reproduces it 100%.

It's triggered by `[vite] page reload @stylex-dev.css`, which is also an issue.

**Comment by dai-shi** [comment]
I'm not sure if this exists in the new version.
Please open a new issue with reproduction steps.

**Comment by rmarscher** [comment]
I hit this error a lot while developing after restarting my dev server. I think this is only a dev server issue. I have never seen this error in production.

If you are stuck in this state, deleting `node_modules/.vite` and/or opening a new browser tab seems to help. I think Chrome keeps some type of connection or service-worker that doesn't clear if you refresh in the current tab.
